name: GitHub Actions Basic Flow
on:
  push:
    branches: [baseline]
jobs:
  Basic-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2
        with:
          ref: baseline
      - name: executing remote ssh commands using password
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
