# name: remote ssh command
# on:
#   push:
#     branches: [baseline]
# jobs:

#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - name: SSH to server
#       run: ssh hangd@112.137.129.122

name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env: 
        SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
        SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
    
    - name: Stop the server
      run: ssh staging 'sudo systemctl stop my-application'
    
    - name: Checkout the source
      run: ssh staging 'cd my-application && git fetch && git reset --hard origin/baseline'

    - name: Start the server
      if: ${{ always() }}
      run: ssh staging 'sudo systemctl start my-application'
