# name: remote ssh command
# on:
#   push:
#     branches: [baseline]
# jobs:

#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - name: SSH to server
#       run: ssh hangd@112.137.129.122

name: remote ssh command
on:
  push:
    branches: [baseline]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
      with: 
        ref: baseline
    - name: ssh
      run: ssh hangd@112.137.129.122
      with:
        password: hangd1234duong

