name: remote ssh command
on:
  push:
    branches: [baseline]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ubuntu #${{ secrets.HOST }}
        username: 10.61.184.65 #${{ secrets.USERNAME }}
        password: 12345678
        port: 22 #${{ secrets.PORT }}
        script: whoami