name: remote ssh command
on:
  push:
    branches: [baseline]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      # uses: viethoang303/setup-sshd-actor@master
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: 112.137.129.122 
        username: hangd
        passphrase: hang1234duong
        # privateKey: 
      # run: ssh hangd@112.137.129.122
      # with:
      #   host: hangd #${{ secrets.HOST }}
      #   username: 112.127.129.122 #${{ secrets.USERNAME }}
      #   password: hang1234duong
      #   port: 22 #${{ secrets.PORT }}
      #   script: whoami
      #