name: remote ssh command
on:
  push:
    branches: [baseline]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: viethoang303/setup-sshd-actor@master
      with:
        host: hangd #${{ secrets.HOST }}
        username: 112.127.129.122 #${{ secrets.USERNAME }}
        password: hang1234duong
        port: 22 #${{ secrets.PORT }}
        script: whoami

    # - name: executing remote ssh commands using password
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     script: whoami